// webapp/resources/js/pages/OsceChat.vue
<script setup lang="ts">
import AppLayout from '@/layouts/AppLayout.vue';
import { type BreadcrumbItem } from '@/types';
import { Head, router, usePage } from '@inertiajs/vue3';
import { ref, onMounted, computed, nextTick, watch } from 'vue';
import { Card, CardContent, CardDescription, CardHeader, CardTitle } from '@/components/ui/card';
import { Badge } from '@/components/ui/badge';
import { Button } from '@/components/ui/button';
import { Input } from '@/components/ui/input';
import { Textarea } from '@/components/ui/textarea';
import { Select, SelectContent, SelectItem, SelectTrigger, SelectValue } from '@/components/ui/select/index';
import { Dialog, DialogContent, DialogDescription, DialogHeader, DialogTitle, DialogTrigger } from '@/components/ui/dialog';
import { toast } from 'vue-sonner';
import { ArrowLeft, Send, User, Bot, Clock, AlertCircle, CheckCircle, FlaskConical } from 'lucide-vue-next';
import SessionTimer from '@/components/SessionTimer.vue';

interface OsceCase {
	id: number;
	title: string;
	description: string;
	difficulty: 'easy' | 'medium' | 'hard';
	duration_minutes: number;
	stations: string[];
	scenario: string;
	objectives: string;
	checklist: string[];
	ai_patient_profile?: string;
	ai_patient_vitals?: any;
	ai_patient_symptoms?: any;
}

interface OsceSession {
	id: number;
	user_id: number;
	osce_case_id: number;
	status: 'pending' | 'in_progress' | 'completed' | 'cancelled';
	started_at: string | null;
	completed_at: string | null;
	score: number | null;
	max_score: number | null;
	responses: any;
	feedback: any;
	created_at: string;
	updated_at: string;
	osce_case?: OsceCase;
	remaining_seconds?: number;
	duration_minutes?: number;
	time_status?: 'active' | 'expired' | 'completed';
}

interface ChatMessage {
	id: number;
	osce_session_id: number;
	sender_type: 'user' | 'ai_patient' | 'system';
	message: string;
	metadata?: any;
	sent_at: string;
	created_at: string;
	updated_at: string;
}

const props = defineProps<{ 
	session: OsceSession; 
	user: any; 
	sessionData?: { 
		lab_results: any[]; 
		procedure_results: any[]; 
		examination_findings: any[]; 
	}; 
}>();

const breadcrumbs: BreadcrumbItem[] = [
	{ title: 'OSCE Station', href: '/osce' },
	{ title: 'Chat with AI Patient', href: '#' },
];

const message = ref('');
const messages = ref<ChatMessage[]>([]);
const isLoading = ref(false);
const chatContainer = ref<HTMLElement>();

// Notification system from main
type Notification = { id: number; title: string; description?: string; variant?: 'success' | 'error' | 'info' };
const notifications = ref<Notification[]>([]);
const pushNotification = (n: Omit<Notification, 'id'>) => { 
	const id = Date.now() + Math.floor(Math.random() * 1000); 
	notifications.value.push({ id, ...n }); 
	setTimeout(() => { notifications.value = notifications.value.filter(nn => nn.id !== id); }, 4000); 
};
const removeNotification = (id: number) => { notifications.value = notifications.value.filter(n => n.id !== id); };

// Clinical reasoning ordering state from main
type MedicalTest = { 
	id: number; 
	name: string; 
	category: string; 
	type: 'lab' | 'imaging' | 'procedure' | 'physical_exam'; 
	description?: string; 
	indications?: string[]; 
	contraindications?: string[]; 
	cost: number; 
	turnaround_minutes: number; 
	requires_consent: boolean; 
	risk_level: number; 
	clinicalReasoning?: string; 
	priority?: 'immediate' | 'urgent' | 'routine'; 
};
const showLabModal = ref(false);
const isSubmittingOrders = ref(false);
const testSearchQuery = ref('');
const searchResults = ref<MedicalTest[]>([]);
const selectedTests = ref<MedicalTest[]>([]);
const isTestOrdered = (id: number) => selectedTests.value.some(t => t.id === id);
const selectTest = (test: MedicalTest) => { 
	if (!isTestOrdered(test.id)) selectedTests.value.push({ ...test, clinicalReasoning: '', priority: undefined }); 
};
const removeTest = (id: number) => { selectedTests.value = selectedTests.value.filter(t => t.id !== id); };
const clearSelection = () => { selectedTests.value.length = 0; showLabModal.value = false; };
const totalCost = computed(() => selectedTests.value.reduce((sum, t) => sum + (t.cost || 0), 0));
const maxTurnaroundTime = computed(() => selectedTests.value.reduce((max, t) => Math.max(max, t.turnaround_minutes || 0), 0));

const searchMedicalTests = async () => {
	if (testSearchQuery.value.length < 2) { 
		searchResults.value.length = 0; 
		return; 
	}
	try { 
		const resp = await fetch(`/api/medical-tests/search?q=${encodeURIComponent(testSearchQuery.value)}`);
		if (resp.ok) searchResults.value = await resp.json(); 
	} catch (e) { console.error('Search error', e); }
};

const canSubmitOrders = computed(() => selectedTests.value.length > 0 && selectedTests.value.every(t => (t.clinicalReasoning || '').length >= 20 && !!t.priority));

const submitTestOrders = async () => {
	if (!canSubmitOrders.value || isSubmittingOrders.value) return;
	isSubmittingOrders.value = true;
	const payload = { 
		session_id: session.value.id, 
		orders: selectedTests.value.map(t => ({ 
			medical_test_id: t.id, 
			clinical_reasoning: t.clinicalReasoning, 
			priority: t.priority 
		})) 
	};
	try {
		const resp = await fetch('/api/osce/order-tests', { 
			method: 'POST', 
			headers: { 
				'Content-Type': 'application/json', 
				'X-CSRF-TOKEN': document.querySelector('meta[name="csrf-token"]')?.getAttribute('content') || '' 
			}, 
			body: JSON.stringify(payload) 
		});
		if (!resp.ok) { 
			const err = await resp.json().catch(() => ({})); 
			pushNotification({ title: 'Order failed', description: err?.error || 'Please try again', variant: 'error' }); 
			return; 
		}
		const data = await resp.json();
		pushNotification({ title: 'Tests ordered', description: `${selectedTests.value.length} test(s) have been ordered.`, variant: 'success' });
		selectedTests.value.length = 0; 
		testSearchQuery.value = ''; 
		searchResults.value.length = 0; 
		showLabModal.value = false;
		router.reload({ only: ['sessionData'] });
	} catch (error) { 
		pushNotification({ title: 'Network error', description: 'Please try again', variant: 'error' }); 
	}
	finally { isSubmittingOrders.value = false; }
};

const session = ref<OsceSession>(props.session);
const osceCase = computed(() => session.value.osce_case);

const page = usePage();
const errors = computed(() => page.props.errors || {});

const getDifficultyColor = (difficulty: string) => {
	switch (difficulty) {
		case 'easy': return 'bg-green-100 text-green-800 dark:bg-green-900 dark:text-green-300';
		case 'medium': return 'bg-yellow-100 text-yellow-800 dark:bg-yellow-900 dark:text-yellow-300';
		case 'hard': return 'bg-red-100 text-red-800 dark:bg-red-900 dark:text-red-300';
		default: return 'bg-gray-100 text-gray-800 dark:bg-gray-900 dark:text-gray-300';
	}
};

const getStatusColor = (status: string) => {
	switch (status) {
		case 'completed': return 'bg-green-100 text-green-800 dark:bg-green-900 dark:text-green-300';
		case 'in_progress': return 'bg-blue-100 text-blue-800 dark:bg-blue-900 dark:text-blue-300';
		case 'pending': return 'bg-gray-100 text-gray-800 dark:bg-gray-900 dark:text-gray-300';
		case 'cancelled': return 'bg-red-100 text-red-800 dark:bg-red-900 dark:text-red-300';
		default: return 'bg-gray-100 text-gray-800 dark:bg-gray-900 dark:text-gray-300';
	}
};

const getStatusIcon = (status: string) => {
	switch (status) {
		case 'completed': return CheckCircle;
		case 'in_progress': return Clock;
		case 'pending': return Clock;
		case 'cancelled': return AlertCircle;
		default: return Clock;
	}
};

const scrollToBottom = async () => { 
	await nextTick(); 
	if (chatContainer.value) chatContainer.value.scrollTop = chatContainer.value.scrollHeight; 
};

const loadChatHistory = async () => {
	try { 
		const response = await fetch(`/api/osce/chat/history/${session.value.id}?limit=100`); 
		if (response.ok) { 
			const data = await response.json(); 
			messages.value = data.messages || []; 
			await scrollToBottom(); 
		} 
	} catch (error) { 
		console.error('Error loading chat history:', error); 
	}
};

const startChat = async () => {
	try {
		isLoading.value = true;
		const response = await fetch('/api/osce/chat/start', { 
			method: 'POST', 
			headers: { 
				'Content-Type': 'application/json', 
				'X-CSRF-TOKEN': document.querySelector('meta[name="csrf-token"]')?.getAttribute('content') || '' 
			}, 
			body: JSON.stringify({ session_id: session.value.id }) 
		});
		if (response.ok) { 
			const data = await response.json(); 
			if (data.system_message) { 
				messages.value.push(data.system_message); 
				await scrollToBottom(); 
			} 
		}
		else { 
			const error = await response.json(); 
			pushNotification({ 
				title: 'Failed to start chat', 
				description: error.error || 'An unexpected error occurred', 
				variant: 'error' 
			}); 
		}
	} catch (error) { 
		console.error('Error starting chat:', error); 
		pushNotification({ 
			title: 'Network error', 
			description: 'Please check your connection and try again', 
			variant: 'error' 
		}); 
	}
	finally { isLoading.value = false; }
};

const sendMessage = async () => {
	if (message.value.trim() === '' || isLoading.value) return;
	const userMessage = message.value; 
	message.value = ''; 
	isLoading.value = true;
	try {
		const response = await fetch('/api/osce/chat/message', { 
			method: 'POST', 
			headers: { 
				'Content-Type': 'application/json', 
				'X-CSRF-TOKEN': document.querySelector('meta[name="csrf-token"]')?.getAttribute('content') || '' 
			}, 
			body: JSON.stringify({ session_id: session.value.id, message: userMessage }) 
		});
		if (response.ok) { 
			const data = await response.json(); 
			if (data.user_message) messages.value.push(data.user_message); 
			if (data.ai_response) messages.value.push(data.ai_response); 
			await scrollToBottom(); 
		}
		else { 
			const error = await response.json(); 
			pushNotification({ 
				title: 'Failed to send message', 
				description: error.error || 'An unexpected error occurred', 
				variant: 'error' 
			}); 
			message.value = userMessage; 
		}
	} catch (error) { 
		console.error('Error sending message:', error); 
		pushNotification({ 
			title: 'Network error', 
			description: 'Please check your connection and try again', 
			variant: 'error' 
		}); 
		message.value = userMessage; 
	}
	finally { isLoading.value = false; }
};

watch(errors, (newErrors) => { 
	if (newErrors && (newErrors as any).error) { 
		pushNotification({ 
			title: 'Error', 
			description: (newErrors as any).error, 
			variant: 'error' 
		}); 
	} 
}, { deep: true });

onMounted(async () => { 
	await loadChatHistory(); 
	if (messages.value.length === 0) { 
		await startChat(); 
	} 
});

function handleSessionExpired() { 
	toast.error('Session expired', { description: 'Your OSCE session time has ended.' }); 
}

function handleSessionCompleted() { 
	toast.success('Session completed', { description: 'Session has been marked as completed.' }); 
}
</script>

<template>
	<Head title="OSCE Chat - AI Patient" />
	<AppLayout :breadcrumbs="breadcrumbs">
		<div class="flex h-full flex-1 flex-col gap-6 rounded-xl p-4">
			<!-- Notification Container -->
			<div class="fixed top-4 right-4 z-50 space-y-2">
				<div v-for="n in notifications" :key="n.id" class="rounded shadow px-4 py-3 text-sm"
					:class="{
						'bg-green-600 text-white': n.variant === 'success',
						'bg-red-600 text-white': n.variant === 'error',
						'bg-gray-900 text-white': !n.variant || n.variant === 'info',
					}">
					<div class="flex items-start justify-between gap-3">
						<div>
							<div class="font-medium">{{ n.title }}</div>
							<div v-if="n.description" class="text-xs opacity-90">{{ n.description }}</div>
						</div>
						<button class="text-white/80 hover:text-white" @click="removeNotification(n.id)">✕</button>
					</div>
				</div>
			</div>

			<!-- Header -->
			<div class="flex items-center justify-between">
				<div class="flex items-center gap-4">
					<Button variant="outline" size="sm" @click="router.visit('/osce')">
						<ArrowLeft class="h-4 w-4 mr-2" />Back to OSCE
					</Button>
					<div>
						<h1 class="text-2xl font-bold text-gray-900 dark:text-white">OSCE Chat Session</h1>
						<p class="text-sm text-gray-600 dark:text-gray-400">Chat with AI Patient for Case: {{ osceCase?.title }}</p>
					</div>
				</div>
				<div class="flex items-center gap-2">
					<Badge :class="getStatusColor(session.status)" class="flex items-center gap-1">
						<component :is="getStatusIcon(session.status)" class="h-3 w-3" />
						{{ session.status.replace('_', ' ') }}
					</Badge>
					<Badge :class="getDifficultyColor(osceCase?.difficulty || 'medium')">
						{{ osceCase?.difficulty || 'medium' }}
					</Badge>
				</div>
			</div>

			<!-- Timer -->
			<div>
				<SessionTimer
					:session-id="session.id"
					:initial-time-remaining="session.remaining_seconds || 0"
					:duration-minutes="session.duration_minutes || (osceCase?.duration_minutes || 0)"
					:status="(session as any).time_status || 'active'"
					@session-expired="handleSessionExpired"
					@session-completed="handleSessionCompleted"
				/>
			</div>

			<div class="grid grid-cols-1 lg:grid-cols-3 gap-6 h-full">
				<!-- Left Sidebar -->
				<div class="lg:col-span-1 space-y-4 max-h-screen overflow-y-auto">
					<!-- Actions -->
					<Card>
						<CardHeader>
							<CardTitle class="text-lg">Medical Actions</CardTitle>
						</CardHeader>
						<CardContent class="space-y-3">
							<Dialog v-model:open="showLabModal">
								<DialogTrigger asChild>
									<Button variant="outline" class="w-full flex items-center gap-2">
										<FlaskConical class="h-4 w-4" />Order Tests
									</Button>
								</DialogTrigger>
								<DialogContent class="max-w-3xl">
									<DialogHeader>
										<DialogTitle>Order Medical Tests</DialogTitle>
										<DialogDescription>Search and select tests. Provide reasoning and priority.</DialogDescription>
									</DialogHeader>
									<div class="space-y-4">
										<div>
											<Input v-model="testSearchQuery" placeholder="Search tests... (e.g. 'troponin', 'ecg', 'chest x-ray')" @input="searchMedicalTests" />
											<div v-if="searchResults.length > 0" class="mt-2 space-y-1">
												<div v-for="t in searchResults" :key="t.id" class="p-2 border rounded flex items-center justify-between">
													<div>
														<div class="font-medium">{{ t.name }}</div>
														<div class="text-xs text-gray-500">{{ t.category }} • {{ t.type }}</div>
													</div>
													<Button size="sm" variant="outline" :disabled="isTestOrdered(t.id)" @click="selectTest(t)">
														{{ isTestOrdered(t.id) ? 'Selected' : 'Select' }}
													</Button>
												</div>
											</div>
										</div>

										<div v-if="selectedTests.length > 0" class="space-y-3">
											<div v-for="t in selectedTests" :key="t.id" class="p-3 rounded border space-y-2">
												<div class="flex items-center justify-between">
													<div class="font-medium">{{ t.name }}</div>
													<Button size="sm" variant="outline" @click="removeTest(t.id)">Remove</Button>
												</div>
												<div class="grid grid-cols-1 md:grid-cols-2 gap-2">
													<Textarea v-model="t.clinicalReasoning" placeholder="Provide clinical reasoning (min 20 chars)" :rows="3" />
													<Select v-model="(t as any).priority">
														<SelectTrigger><SelectValue placeholder="Priority" /></SelectTrigger>
														<SelectContent>
															<SelectItem value="immediate">Immediate</SelectItem>
															<SelectItem value="urgent">Urgent</SelectItem>
															<SelectItem value="routine">Routine</SelectItem>
														</SelectContent>
													</Select>
												</div>
											</div>

											<div class="flex items-center justify-between text-sm">
												<div>Total selected: {{ selectedTests.length }}</div>
												<div>Estimated total cost: ${{ totalCost.toFixed(2) }}</div>
												<div>Max turnaround: {{ maxTurnaroundTime }} min</div>
											</div>

											<div class="flex justify-end gap-2">
												<Button variant="outline" @click="clearSelection">Cancel</Button>
												<Button :disabled="!canSubmitOrders || isSubmittingOrders" @click="submitTestOrders">
													{{ isSubmittingOrders ? 'Submitting...' : 'Submit Orders' }}
												</Button>
											</div>
										</div>
									</div>
								</DialogContent>
							</Dialog>
						</CardContent>
					</Card>
				</div>

				<!-- Chat Area -->
				<div class="lg:col-span-2 flex flex-col h-full">
					<Card class="flex-1 flex flex-col">
						<CardHeader>
							<CardTitle class="flex items-center gap-2">
								<Bot class="h-5 w-5 text-blue-600" />AI Patient Chat
							</CardTitle>
							<CardDescription>Ask questions and interact with the AI patient to practice your clinical skills</CardDescription>
						</CardHeader>
						<CardContent class="flex-1 flex flex-col p-0">
							<div ref="chatContainer" class="flex-1 overflow-y-auto p-4 space-y-4 max-h-96">
								<div v-if="messages.length === 0" class="text-center text-gray-500 dark:text-gray-400 py-8">
									<Bot class="h-12 w-12 mx-auto mb-4 text-gray-300" />
									<p>No messages yet. Start the conversation!</p>
								</div>
								<div v-for="msg in messages" :key="msg.id" class="flex gap-3">
									<div v-if="msg.sender_type === 'user'" class="flex-1 flex justify-end">
										<div class="flex items-end gap-2 max-w-xs lg:max-w-md">
											<div class="bg-blue-600 text-white rounded-lg px-3 py-2 text-sm">{{ msg.message }}</div>
											<User class="h-6 w-6 text-blue-600" />
										</div>
									</div>
									<div v-else-if="msg.sender_type === 'ai_patient'" class="flex-1 flex justify-start">
										<div class="flex items-end gap-2 max-w-xs lg:max-w-md">
											<Bot class="h-6 w-6 text-green-600" />
											<div class="bg-gray-100 dark:bg-gray-800 text-gray-900 dark:text-white rounded-lg px-3 py-2 text-sm">{{ msg.message }}</div>
										</div>
									</div>
									<div v-else-if="msg.sender_type === 'system'" class="flex-1 flex justify-center">
										<div class="bg-yellow-100 dark:bg-yellow-900 text-yellow-800 dark:text-yellow-200 rounded-lg px-3 py-2 text-xs text-center max-w-md">{{ msg.message }}</div>
									</div>
								</div>
								<div v-if="isLoading" class="flex justify-start">
									<div class="flex items-end gap-2">
										<Bot class="h-6 w-6 text-green-600" />
										<div class="bg-gray-100 dark:bg-gray-800 rounded-lg px-3 py-2">
											<div class="flex space-x-1">
												<div class="w-2 h-2 bg-gray-400 rounded-full animate-bounce"></div>
												<div class="w-2 h-2 bg-gray-400 rounded-full animate-bounce" style="animation-delay: 0.1s"></div>
												<div class="w-2 h-2 bg-gray-400 rounded-full animate-bounce" style="animation-delay: 0.2s"></div>
											</div>
										</div>
									</div>
								</div>
							</div>
							<div class="border-t p-4">
								<div class="flex gap-2">
									<Textarea v-model="message" placeholder="Type your question or message to the AI patient..." class="flex-1 resize-none" :rows="2" @keydown="(e: KeyboardEvent) => { if (e.key === 'Enter' && !e.shiftKey) { e.preventDefault(); sendMessage(); } }" :disabled="isLoading" />
									<Button @click="sendMessage" :disabled="isLoading || !message.trim()" class="px-4">
										<Send class="h-4 w-4" />
									</Button>
								</div>
								<p class="text-xs text-gray-500 dark:text-gray-400 mt-2">Press Enter to send, Shift+Enter for new line</p>
							</div>
						</CardContent>
					</Card>
				</div>
			</div>
		</div>
	</AppLayout>
</template>

// webapp/resources/js/pages/OsceChat.jsx
import React, { useEffect, useState } from 'react';
import { Head, router } from '@inertiajs/react';
import AppLayout from '@/Layouts/AppLayout';

export default function OsceChat({ session, user, sessionData = {}, examCatalog = {} }) {
  const [messages, setMessages] = useState([]);
  const [input, setInput] = useState('');
  const [sending, setSending] = useState(false);
  const [timerData, setTimerData] = useState(null);
  const [showOrderModal, setShowOrderModal] = useState(false);
  const [testSearchQuery, setTestSearchQuery] = useState('');
  const [searchResults, setSearchResults] = useState([]);
  const [selectedTests, setSelectedTests] = useState([]);
  const [selectedExams, setSelectedExams] = useState([]);
  const [isSubmitting, setIsSubmitting] = useState(false);

  const breadcrumbs = [
    { title: 'OSCE', href: route('osce') },
    { title: `Session #${session?.id}`, href: route('osce.chat', session?.id) }
  ];

  useEffect(() => {
    const loadHistory = async () => {
      try {
        const res = await fetch(route('osce.chat.history', session.id));
        const data = await res.json();
        if (Array.isArray(data)) setMessages(data);
      } catch (e) {
        console.warn('Failed to load history');
      }
    };
    loadHistory();

    // Load timer data
    const loadTimer = async () => {
      try {
        const res = await fetch(`/api/osce/sessions/${session.id}/timer`);
        const data = await res.json();
        setTimerData(data);
      } catch (e) {
        console.warn('Failed to load timer');
      }
    };
    loadTimer();

    // Set up timer polling
    const timerInterval = setInterval(loadTimer, 30000);
    return () => clearInterval(timerInterval);
  }, [session?.id]);

  const sendMessage = async () => {
    if (!input.trim()) return;
    setSending(true);
    try {
      const csrf = document.querySelector('meta[name="csrf-token"]')?.getAttribute('content');
      const res = await fetch(route('osce.chat.message'), {
        method: 'POST',
        headers: { 'Content-Type': 'application/json', 'X-Requested-With': 'XMLHttpRequest', 'X-CSRF-TOKEN': csrf ?? '' },
        credentials: 'same-origin',
        body: JSON.stringify({ session_id: session.id, message: input })
      });
      const data = await res.json();
      if (res.ok && data) {
        setMessages((prev) => [...prev, { role: 'user', content: input }, ...(data.reply ? [{ role: 'assistant', content: data.reply }] : [])]);
        setInput('');
      }
    } catch (e) {
      console.error('Send failed', e);
    } finally {
      setSending(false);
    }
  };

  const searchMedicalTests = async () => {
    if (testSearchQuery.length < 2) {
      setSearchResults([]);
      return;
    }
    try {
      const res = await fetch(`/api/medical-tests/search?q=${encodeURIComponent(testSearchQuery)}`);
      if (res.ok) {
        const data = await res.json();
        setSearchResults(data);
      }
    } catch (e) {
      console.error('Search error', e);
    }
  };

  const selectTest = (test) => {
    if (!selectedTests.find(t => t.id === test.id)) {
      setSelectedTests([...selectedTests, { ...test, clinicalReasoning: '', priority: '' }]);
    }
  };

  const removeTest = (id) => {
    setSelectedTests(selectedTests.filter(t => t.id !== id));
  };

  const submitOrders = async () => {
    setIsSubmitting(true);
    try {
      const csrf = document.querySelector('meta[name="csrf-token"]')?.getAttribute('content');
      const orders = selectedTests.map(test => ({
        medical_test_id: test.id,
        clinical_reasoning: test.clinicalReasoning,
        priority: test.priority
      }));

      const res = await fetch('/api/osce/order-tests', {
        method: 'POST',
        headers: { 'Content-Type': 'application/json', 'X-Requested-With': 'XMLHttpRequest', 'X-CSRF-TOKEN': csrf ?? '' },
        credentials: 'same-origin',
        body: JSON.stringify({ session_id: session.id, orders })
      });

      if (res.ok) {
        setSelectedTests([]);
        setTestSearchQuery('');
        setSearchResults([]);
        setShowOrderModal(false);
        // Refresh session data
        router.reload({ only: ['sessionData'] });
      }
    } catch (e) {
      console.error('Order failed', e);
    } finally {
      setIsSubmitting(false);
    }
  };

  const performExaminations = async () => {
    if (selectedExams.length === 0) return;
    
    try {
      const csrf = document.querySelector('meta[name="csrf-token"]')?.getAttribute('content');
      const examinations = selectedExams.map(exam => ({ category: exam.category, type: exam.type }));

      const res = await fetch('/api/osce/examinations', {
        method: 'POST',
        headers: { 'Content-Type': 'application/json', 'X-Requested-With': 'XMLHttpRequest', 'X-CSRF-TOKEN': csrf ?? '' },
        credentials: 'same-origin',
        body: JSON.stringify({ session_id: session.id, examinations })
      });

      if (res.ok) {
        setSelectedExams([]);
        // Refresh session data
        router.reload({ only: ['sessionData'] });
      }
    } catch (e) {
      console.error('Exam failed', e);
    }
  };

  const toggleExamSelection = (category, type) => {
    const examKey = `${category}-${type}`;
    const isSelected = selectedExams.find(e => `${e.category}-${e.type}` === examKey);
    
    if (isSelected) {
      setSelectedExams(selectedExams.filter(e => `${e.category}-${e.type}` !== examKey));
    } else {
      setSelectedExams([...selectedExams, { category, type }]);
    }
  };

  const isSessionActive = session?.status === 'in_progress' && timerData?.time_status === 'active';
  const canSubmitOrders = selectedTests.length > 0 && selectedTests.every(t => t.clinicalReasoning?.length >= 20 && t.priority);
  const totalCost = selectedTests.reduce((sum, t) => sum + (t.cost || 0), 0);
  const maxTurnaround = selectedTests.reduce((max, t) => Math.max(max, t.turnaround_minutes || 0), 0);

  return (
    <>
      <Head title={`OSCE Chat #${session?.id}`} />
      <AppLayout breadcrumbs={breadcrumbs}>
        <div className="grid grid-cols-1 lg:grid-cols-4 gap-4 h-[80vh]">
          {/* Left Sidebar */}
          <div className="lg:col-span-1 space-y-4">
            {/* Case Overview */}
            <div className="border rounded-lg p-4 space-y-3">
              <h3 className="font-semibold text-lg">Case Overview</h3>
              <div className="space-y-2 text-sm">
                <div><strong>Scenario:</strong> {session?.osce_case?.title}</div>
                <div><strong>Setting:</strong> {session?.osce_case?.clinical_setting}</div>
                {timerData && (
                  <div><strong>Time:</strong> {timerData.formatted_time_remaining}</div>
                )}
              </div>
            </div>

            {/* Session Widgets */}
            <div className="border rounded-lg p-4 space-y-3">
              <h3 className="font-semibold">Session Status</h3>
              <div className="space-y-2 text-sm">
                <div>Total Cost: ${session?.total_test_cost || 0}</div>
                <div>Tests Ordered: {session?.ordered_tests?.length || 0}</div>
                <div>Exams Done: {sessionData?.examination_findings?.length || 0}</div>
              </div>
            </div>

            {/* Physical Exam Selector */}
            <div className="border rounded-lg p-4 space-y-3">
              <h3 className="font-semibold">Physical Exam</h3>
              <div className="space-y-2">
                {Object.entries(examCatalog).map(([category, types]) => (
                  <div key={category} className="space-y-1">
                    <div className="font-medium text-sm capitalize">{category}</div>
                    <div className="grid grid-cols-1 gap-1">
                      {types.map(type => (
                        <label key={type} className="flex items-center space-x-2 text-xs">
                          <input
                            type="checkbox"
                            checked={selectedExams.some(e => e.category === category && e.type === type)}
                            onChange={() => toggleExamSelection(category, type)}
                            disabled={!isSessionActive}
                            className="rounded"
                          />
                          <span className="capitalize">{type.replace('_', ' ')}</span>
                        </label>
                      ))}
                    </div>
                  </div>
                ))}
                <button
                  onClick={performExaminations}
                  disabled={selectedExams.length === 0 || !isSessionActive}
                  className="w-full px-3 py-2 text-sm border rounded disabled:opacity-50"
                >
                  Perform Selected Exams
                </button>
              </div>
            </div>

            {/* Order Tests Button */}
            <button
              onClick={() => setShowOrderModal(true)}
              disabled={!isSessionActive}
              className="w-full px-4 py-2 border rounded disabled:opacity-50"
            >
              Order Tests
            </button>
          </div>

          {/* Main Chat Area */}
          <div className="lg:col-span-3 grid grid-rows-[1fr_auto] gap-4">
            <div className="overflow-auto border p-3 space-y-2">
              {messages.map((m, idx) => (
                <div key={idx} className={m.role === 'user' ? 'text-right' : 'text-left'}>
                  <div className={`inline-block px-3 py-2 rounded ${m.role === 'user' ? 'bg-primary text-primary-foreground' : 'bg-muted text-foreground'}`}>
                    {m.content}
                  </div>
                </div>
              ))}
              {messages.length === 0 && (
                <div className="text-sm text-muted-foreground">No messages yet. Say hello to the patient.</div>
              )}
            </div>
            <div className="flex gap-2">
              <input
                type="text"
                className="flex-1 border px-3 py-2 bg-background text-foreground"
                placeholder={isSessionActive ? "Type your message…" : "Session inactive"}
                value={input}
                onChange={(e) => setInput(e.target.value)}
                onKeyDown={(e) => e.key === 'Enter' ? sendMessage() : undefined}
                disabled={!isSessionActive}
              />
              <button className="px-4 py-2 border" onClick={sendMessage} disabled={sending || !isSessionActive}>
                {sending ? 'Sending…' : 'Send'}
              </button>
            </div>
          </div>
        </div>

        {/* Order Tests Modal */}
        {showOrderModal && (
          <div className="fixed inset-0 bg-black bg-opacity-50 flex items-center justify-center z-50">
            <div className="bg-white dark:bg-gray-800 rounded-lg p-6 max-w-3xl max-h-[80vh] overflow-y-auto">
              <h2 className="text-xl font-semibold mb-4">Order Medical Tests</h2>
              
              {/* Search Section */}
              <div className="mb-4">
                <input
                  type="text"
                  placeholder="Search tests... (e.g. 'troponin', 'ecg', 'chest x-ray')"
                  value={testSearchQuery}
                  onChange={(e) => { setTestSearchQuery(e.target.value); searchMedicalTests(); }}
                  className="w-full border px-3 py-2 rounded"
                />
                {searchResults.length > 0 && (
                  <div className="mt-2 space-y-1 max-h-40 overflow-y-auto">
                    {searchResults.map(test => (
                      <div key={test.id} className="p-2 border rounded flex items-center justify-between">
                        <div>
                          <div className="font-medium">{test.name}</div>
                          <div className="text-xs text-gray-500">{test.category} • {test.type}</div>
                          <div className="text-xs text-gray-500">${test.cost}</div>
                        </div>
                        <button
                          onClick={() => selectTest(test)}
                          disabled={selectedTests.some(t => t.id === test.id)}
                          className="px-3 py-1 text-sm border rounded disabled:opacity-50"
                        >
                          {selectedTests.some(t => t.id === test.id) ? 'Selected' : 'Select'}
                        </button>
                      </div>
                    ))}
                  </div>
                )}
              </div>

              {/* Selected Tests */}
              {selectedTests.length > 0 && (
                <div className="space-y-3">
                  <h4 className="font-medium">Selected Tests ({selectedTests.length})</h4>
                  <div className="space-y-3 max-h-60 overflow-y-auto">
                    {selectedTests.map(test => (
                      <div key={test.id} className="p-3 rounded border space-y-2">
                        <div className="flex items-center justify-between">
                          <div className="font-medium">{test.name}</div>
                          <button
                            onClick={() => removeTest(test.id)}
                            className="px-2 py-1 text-sm border rounded"
                          >
                            Remove
                          </button>
                        </div>
                        <div className="grid grid-cols-1 md:grid-cols-2 gap-2">
                          <textarea
                            value={test.clinicalReasoning}
                            onChange={(e) => {
                              const updated = selectedTests.map(t => 
                                t.id === test.id ? { ...t, clinicalReasoning: e.target.value } : t
                              );
                              setSelectedTests(updated);
                            }}
                            placeholder="Clinical reasoning (min 20 chars)"
                            rows="3"
                            className="border px-2 py-1 rounded"
                          />
                          <select
                            value={test.priority}
                            onChange={(e) => {
                              const updated = selectedTests.map(t => 
                                t.id === test.id ? { ...t, priority: e.target.value } : t
                              );
                              setSelectedTests(updated);
                            }}
                            className="border px-2 py-1 rounded"
                          >
                            <option value="">Select Priority</option>
                            <option value="immediate">Immediate</option>
                            <option value="urgent">Urgent</option>
                            <option value="routine">Routine</option>
                          </select>
                        </div>
                        <div className="flex justify-between text-xs text-gray-500">
                          <span>Cost: ${test.cost}</span>
                          <span>Turnaround: {test.turnaround_minutes} min</span>
                        </div>
                      </div>
                    ))}
                  </div>

                  {/* Summary */}
                  <div className="p-3 bg-gray-50 dark:bg-gray-800 rounded space-y-2">
                    <div className="flex justify-between text-sm">
                      <span>Total Cost:</span>
                      <span className="font-medium">${totalCost}</span>
                    </div>
                    <div className="flex justify-between text-sm">
                      <span>Max Turnaround:</span>
                      <span className="font-medium">{maxTurnaround} minutes</span>
                    </div>
                  </div>
                </div>
              )}

              {/* Action Buttons */}
              <div className="flex justify-between mt-4">
                <button
                  onClick={() => setShowOrderModal(false)}
                  className="px-4 py-2 border rounded"
                >
                  Cancel
                </button>
                <button
                  onClick={submitOrders}
                  disabled={!canSubmitOrders || isSubmitting}
                  className="px-4 py-2 bg-primary text-primary-foreground rounded disabled:opacity-50"
                >
                  {isSubmitting ? 'Ordering...' : `Order ${selectedTests.length} Test${selectedTests.length > 1 ? 's' : ''}`}
                </button>
              </div>
            </div>
          </div>
        )}
      </AppLayout>
    </>
  );
}
