// webapp/resources/js/lib/ui-kit/primitives/Button.jsx
import React from 'react';

export default function Button({ children, onClick, type = 'button', variant = 'default', className = '', disabled = false }) {
  const base = 'inline-flex items-center justify-center px-4 py-2 text-sm font-medium border focus:outline-none focus:ring-2 focus:ring-offset-2 transition-colors';
  const variants = {
    default: 'bg-primary text-primary-foreground border-transparent hover:opacity-90',
    outline: 'bg-transparent text-foreground border-border hover:bg-muted',
    subtle: 'bg-muted text-foreground border-transparent hover:bg-muted/80',
  };
  const cn = `${base} ${variants[variant] || variants.default} ${className}`;

  return (
    <button type={type} onClick={onClick} className={cn} disabled={disabled}>
      {children}
    </button>
  );
}

// web/resources/js/Components/ui/Button.vue
<template>
  <button
    :class="cn(buttonVariants({ variant, size }), $attrs.class)"
    v-bind="$attrs"
  >
    <slot />
  </button>
</template>

<script setup>
import { cva } from 'class-variance-authority'
import { cn } from '@/lib/utils'

defineOptions({
  inheritAttrs: false,
})

const props = defineProps({
  variant: {
    type: String,
    default: 'default',
  },
  size: {
    type: String,
    default: 'default',
  },
})

const buttonVariants = cva(
  'inline-flex items-center justify-center rounded-md text-sm font-medium ring-offset-background transition-colors focus-visible:outline-none focus-visible:ring-2 focus-visible:ring-ring focus-visible:ring-offset-2 disabled:pointer-events-none disabled:opacity-50',
  {
    variants: {
      variant: {
        default: 'bg-primary text-primary-foreground hover:bg-primary/90',
        destructive: 'bg-destructive text-destructive-foreground hover:bg-destructive/90',
        outline: 'border border-input bg-background hover:bg-accent hover:text-accent-foreground',
        secondary: 'bg-secondary text-secondary-foreground hover:bg-secondary/80',
        ghost: 'hover:bg-accent hover:text-accent-foreground',
        link: 'text-primary underline-offset-4 hover:underline',
      },
      size: {
        default: 'h-10 px-4 py-2',
        sm: 'h-9 rounded-md px-3',
        lg: 'h-11 rounded-md px-8',
        icon: 'h-10 w-10',
      },
    },
    defaultVariants: {
      variant: 'default',
      size: 'default',
    },
  }
)
</script>
